### ISSUE TITLE
Wrong C-Cast in patch

### ISSUE THREAD

**Issue by messi1** [bbvch/pru-farbsort#6]
The C-Cast in the patch  0001-pru_virtio_ring-make-it-compile.patch is wrong. struct is missing
It should be:
+       vr->desc = (struct vring_desc *)p;
+       vr->avail = (struct vring_avail *)((char *)p + num*sizeof(struct vring_desc));
+       vr->used = (struct vring_used *)(uintptr_t)(((uint64_t)&vr->avail->ring[num]
                + sizeof(uint16_t) + align-1) & ~(align - 1));

**Comment by bernedom** [comment]
Do you want to create pull request for it? It might be a bit of time, until I can get back to the project

**Comment by messi1** [comment]
Fixed it!
